name: git-commit

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - git-commit

jobs:
  git-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Git settings
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
